Contact Form
donice/Portfolio-Microverse pull request #6
Opened 2023-06-14 14:14 UTC by donice

In the pull request, I:
- Implemented the contact form
- Styled the form
- Intergrated the Form Spree service to make a post request

2023-06-14 15:04 UTC, Gambit142 requested changes
Hi @donice @HossainAraf , 

Good job so far!

## Highlights
- Use of required HTML validation ✔️ 
- Set up Formspree on the for correctly ✔️
- Use of semantic HTML ✔️   

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-14 15:04 UTC, Gambit142 commented on index.html
> +        </div>
- [ ] Please make the width of the `textarea` element to be the same as that of the other two `input` elements. This way, your design will be identical to that of the Figma design that you chose. 👍 💻 

| Your Design  | Figma Template |
| ------------- | ------------- |
| ![Screenshot_2023-06-14 154453](https://github.com/donice/Portfolio-Microverse/assets/77106962/c5daddb2-5d06-476a-aa65-696af73b1dda) | ![image](https://github.com/donice/Portfolio-Microverse/assets/77106962/30a0019b-4918-496b-bbb4-10e6f4e9302d)  |

2023-06-14 15:04 UTC, Gambit142 commented on index.html
> +      </form>
- [ ] Please adjust the width of the form button to look identical to that of the Figma design. The current width is shorter than that of the Figma design. 💻 

| Your Design  | Figma Template |
| ------------- | ------------- |
| ![Screenshot_2023-06-14 155104](https://github.com/donice/Portfolio-Microverse/assets/77106962/842f9739-05c2-4a9a-827a-5f23ef4e750e) | ![image](https://github.com/donice/Portfolio-Microverse/assets/77106962/40b2e30c-02c4-4ff7-b86c-8442db5c63f7)  |

#### Hint: It should be the same width as the input elements. 😎

2023-06-14 15:04 UTC, Gambit142 commented on index.html
>          open_in_new
- [ ] Based on the Figma design for your template, the footer should occupy the bottom part of the page. Your footer design has white space at the bottom of the page. Kindly adjust this. 👍 😎 

| Your Design  | Figma Template |
| ------------- | ------------- |
|
![Screenshot_2023-06-14 160015](https://github.com/donice/Portfolio-Microverse/assets/77106962/d31c0999-3a34-4896-a92b-9f870e1006a2) | ![image](https://github.com/donice/Portfolio-Microverse/assets/77106962/d9cde71c-5185-43d8-b258-c758547e1872)  |

2023-06-14 20:45 UTC, Owusu-Desmond requested changes
Hi @donice , :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 20:45 UTC, Owusu-Desmond commented on style.css
> +  width: 100%;
- [ ] As requested by the previous code reviewer, the width of the textarea field is to be the same as that of the other two input elements. This way, your design will be identical to that of the Figma design that you chose. :point_down: 

  ### Your design
  [Screencast from 06-14-2023 08:14:11 PM.webm](https://github.com/donice/Portfolio-Microverse/assets/92303891/9432a20b-e7f1-43af-bafa-bfb1caddb08e)
  
  ### Figma design
  ![image](https://github.com/donice/Portfolio-Microverse/assets/92303891/583529b1-539b-4145-ba38-6a18cb12ae7a)

- [ ] While you were working on the requested changes, your project is having horizontal overflow on mobile view so make sure that you remove this overflow, as you can see in the video above to make your project responsive :+1:

2023-06-14 20:45 UTC, Owusu-Desmond commented on index.html
>          open_in_new
- [ ] As requested by the previous reviewer, Based on the Figma design for your template, the footer should occupy the bottom part of the page. Your footer design has white space at the bottom of the page. Kindly adjust this. :+1:

  ### Your design
  ![image](https://github.com/donice/Portfolio-Microverse/assets/92303891/a449226e-019a-4efc-bf5d-7cdbf263cd9b)
  
  ### Figma design
  ![image](https://github.com/donice/Portfolio-Microverse/assets/92303891/baa48967-10c8-4e63-b446-7db814ad23d8)

2023-06-17 14:42 UTC, Ofarouq310 reviewed
Hi @donice, ✋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![giphy](https://github.com/donice/Portfolio-Microverse/assets/102612396/f92bf45e-3449-4c24-b14c-917393a27fb5)

## 🔴 Invalid Code Review Request

- You have used the wrong project on the dashboard to review your contact form.

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-17 14:44 UTC, donice commented
Hello @Ofarouq310 
I really do not understand the details of your reviews

2023-06-17 14:49 UTC, Ofarouq310 commented
@donice 
- Kindly note that you have submitted the wrong project to be reviewed.
On your dashboard, you have used your "Portfolio: Desktop version" instead of "Portfolio: Contact form". 
Hope that clarifies.

2023-06-17 18:12 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @donice , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/QBSi1K0yOp1WDGyUFZ/giphy.gif"/>

## Highlights :fire: 
- All requested changes implemented :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 20:47 UTC, merged